version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  ignore:
  - dependency-name: ember-cli
    versions:
    - ">= 0"
  - dependency-name: sass
    versions:
    - 1.32.11
  - dependency-name: ember-cli-babel
    versions:
    - 7.26.2
    - 7.26.3
  - dependency-name: release-it
    versions:
    - 14.5.0
  - dependency-name: ember-template-lint
    versions:
    - 3.0.0
    - 3.0.1
    - 3.1.1
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.16
