name: CI Build

on:
  pull_request: {}
  push:
    branches:
      - main
    tags:
      - v*

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true      
    
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: 'Lint'
        run: |
          pnpm lint:hbs
          pnpm lint:js    

  test:
    name: Basic tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: 'Basic Tests'
        run: pnpm test-fast

  # runs slow end-to-end tests, parallelizing yarn and npm cases
  test-end-to-end:
    name: End-to-end tests (${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: 'End-to-end Tests'
        uses: GabrielBB/xvfb-action@v1
        with:
          run: pnpm test-slow
          
  automerge:
    needs: [lint, test, test-end-to-end]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.2.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}     
