name: CI Build

on:
  pull_request: {}
  push:
    branches:
      - main
    tags:
      - v*

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true      
    
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - run: yarn install --frozen-lockfile --network-timeout 100000

      - name: 'Lint'
        run: |
          yarn lint:hbs
          yarn lint:js    

  test:
    name: Basic tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - run: yarn install --frozen-lockfile --network-timeout 100000

      - name: 'Basic Tests'
        run: yarn test-fast

  # runs slow end-to-end tests, parallelizing yarn and npm cases
  test-end-to-end:
    name: End-to-end tests (${{ matrix.os }}/${{ matrix.package-manager }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        package-manager: ['npm', 'yarn']

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - run: yarn install --frozen-lockfile --network-timeout 100000

      - name: 'End-to-end Tests (${{ matrix.package-manager }})'
        uses: GabrielBB/xvfb-action@v1
        with:
          run: yarn test-slow
        env:
          END_TO_END_TESTS: '${{ matrix.package-manager }}'
          
  automerge:
    needs: [lint, test, test-end-to-end]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.2.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}     
